/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 combat_robot.gltf --transform
Author: ILUSHANDRO (https://sketchfab.com/ILUSHANDRO)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/combat-robot-55fe65bbb4074979ac0cb44850df4ddc
Title: Combat Robot
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/combat_robot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_low_Hands_0.geometry} material={materials.Hands} position={[2.537, -0.533, 2.773]} />
      <mesh geometry={nodes.Cube011_low_Torse_0.geometry} material={materials.Torse} position={[0, 0.485, -0.005]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube017_low_Legs_0.geometry} material={materials.Legs} position={[1.748, -2.581, 0.557]} rotation={[-1.334, 0, 0]} />
      <mesh geometry={nodes.Floor001_Floor_0.geometry} material={materials.Floor} position={[-2.206, -4.828, 2.345]} rotation={[-Math.PI / 2, 0, 0]} scale={2.296} />
    </group>
  )
}

useGLTF.preload('/combat_robot-transformed.glb')
